FROM ruby:3.3.0

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y \
    nodejs \
    npm \
    postgresql-client && \
    npm install -g yarn

# 作業ディレクトリを設定
WORKDIR /myapp

# GemfileとGemfile.lockをコピー
COPY Gemfile Gemfile.lock ./

# bundle installを実行
RUN bundle install

# アプリケーションのコードをコピー
COPY . .

# ポート3000を公開
EXPOSE 3000

# サーバーを起動
CMD ["rails", "server", "-b", "0.0.0.0"]